version: '3.8'

services:
  redis:
    image: redis:alpine

  core:
    build:
      context: .
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build:
      context: .
    command: celery -A src.workers worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - core

  test:
    build: .
    command: pytest tests/
    depends_on:
      - redis
