version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME:-sync_data_logs}

  scheduler:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    command: celery -A scheduler.celery_app beat -l info
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file: .env

  saler:
    build:
      context: .
      dockerfile: saler/Dockerfile
    command: celery -A saler.celery_app worker -l info -Q sale_queue
    depends_on:
      - redis
      - mongo
    volumes:
      - .:/app
    env_file: .env

  importer:
    build:
      context: .
      dockerfile: importer/Dockerfile
    command: celery -A importer.celery_app worker -l info -Q import_queue
    depends_on:
      - redis
      - mongo
    volumes:
      - .:/app
    env_file: .env

  canceller:
    build:
      context: .
      dockerfile: canceller/Dockerfile
    command: celery -A canceller.celery_app worker -l info -Q cancellation_queue
    depends_on:
      - redis
      - mongo
    volumes:
      - .:/app
    env_file: .env