version: '3.8'

services:
  scheduler:
    build: .
    container_name: hermes_scheduler
    command: ["celery", "-A", "app.main.celery_app", "beat", "--loglevel=info", "-s", "/tmp/celerybeat-schedule"]
    volumes:
      - ./app:/app
    env_file:
      - .env

  phieu_nhap_worker:
    build: .
    container_name: hermes_phieu_nhap_worker
    command: ["celery", "-A", "app.main.celery_app", "worker", "-Q", "phieu_nhap_queue", "--loglevel=info", "-c", "2"]
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - scheduler

  phieu_xuat_worker:
    build: .
    container_name: hermes_phieu_xuat_worker
    command: ["celery", "-A", "app.main.celery_app", "worker", "-Q", "phieu_xuat_queue", "--loglevel=info", "-c", "2"]
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - scheduler

  hoa_don_worker:
    build: .
    container_name: hermes_hoa_don_worker
    command: ["celery", "-A", "app.main.celery_app", "worker", "-Q", "hoa_don_queue", "--loglevel=info", "-c", "2"]
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - scheduler
